import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { notifySubscribers } from "@/lib/email/eventNotification";

type EventOperation = "INSERT" | "UPDATE";

const NOTIFICATION_FIELDS = [
  "title",
  "event_date",
  "location",
  "registration_link",
] as const;

type ChangedField = (typeof NOTIFICATION_FIELDS)[number];

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function POST(request: Request) {
  try {
    // ---------------------------------------------------------
    // Verify webhook secret
    // ---------------------------------------------------------

    const webhookSecret = request.headers.get("x-webhook-secret");

    if (!process.env.EVENT_WEBHOOK_SECRET) {
      console.error("EVENT_WEBHOOK_SECRET is not configured.");

      return NextResponse.json(
        { error: "Webhook secret is not configured." },
        { status: 500 }
      );
    }

    if (webhookSecret !== process.env.EVENT_WEBHOOK_SECRET) {
      return NextResponse.json(
        { error: "Unauthorized." },
        { status: 401 }
      );
    }

    // ---------------------------------------------------------
    // Read Supabase webhook payload
    // ---------------------------------------------------------

    const payload = await request.json();

    const operation = payload.type as EventOperation;
    const event = payload.record;
    const oldRecord = payload.old_record;

    // ---------------------------------------------------------
    // Validate operation
    // ---------------------------------------------------------

    if (operation !== "INSERT" && operation !== "UPDATE") {
      return NextResponse.json(
        { error: "Unsupported webhook operation." },
        { status: 400 }
      );
    }

    // ---------------------------------------------------------
    // Validate event
    // ---------------------------------------------------------

    if (!event) {
      return NextResponse.json(
        { error: "No event record found." },
        { status: 400 }
      );
    }

    if (
      !event.id ||
      !event.title ||
      !event.category ||
      !event.event_date ||
      !event.location ||
      !event.organizer
    ) {
      return NextResponse.json(
        { error: "Incomplete event data." },
        { status: 400 }
      );
    }

    // ---------------------------------------------------------
    // INSERT
    //
    // New events are added to the queue.
    //
    // IMPORTANT:
    // created_at is generated by Supabase and becomes the
    // beginning of the 3-hour waiting period.
    // ---------------------------------------------------------

    if (operation === "INSERT") {
      console.log("WEBHOOK: INSERT received", {
    eventId: event.id,
  });

  console.log("WEBHOOK: attempting queue upsert");

      const { error: queueError } = await supabase
        .from("event_notification_queue")
        .upsert(
          {
            event_id: event.id,
          },
          {
            onConflict: "event_id",
            ignoreDuplicates: true,
          }
        );

         console.log("WEBHOOK: queue upsert completed", {
    error: queueError,
  });

      if (queueError) {
        console.error("Failed to queue event:", queueError);
        throw queueError;
      }

      console.log(
        `Event ${event.id} added to notification queue.`
      );

      return NextResponse.json({
        success: true,
        operation: "INSERT",
        queued: true,
      });
    }

    // ---------------------------------------------------------
    // UPDATE
    // ---------------------------------------------------------

    if (!oldRecord) {
      return NextResponse.json(
        { error: "Previous event record not found." },
        { status: 400 }
      );
    }

    const changedFields = NOTIFICATION_FIELDS.filter(
      (field) => oldRecord[field] !== event[field]
    );

    // ---------------------------------------------------------
    // Check meaningful changes
    // ---------------------------------------------------------

    const meaningfulChange = changedFields.length > 0;

    if (!meaningfulChange) {
      console.log(
        `Event ${event.id} was updated, but no notification-relevant ` +
        `fields changed. No email sent.`
      );

      return NextResponse.json({
        success: true,
        operation: "UPDATE",
        notified: false,
        message: "No meaningful event changes detected. No emails sent.",
        sent: 0,
        failed: 0,
      });
    }

    // ---------------------------------------------------------
    // Check whether the event is already waiting in the queue
    // ---------------------------------------------------------

    const { data: queuedEvent, error: queueError } = await supabase
      .from("event_notification_queue")
      .select("id, event_id, created_at, queued_at")
      .eq("event_id", event.id)
      .maybeSingle();

    if (queueError) {
      console.error(
        "Notification queue lookup error:",
        queueError
      );

      throw queueError;
    }

    // ---------------------------------------------------------
    // Event is already queued
    //
    // Do not send an update email.
    // The queue processor will fetch the latest event
    // data directly from the events table.
    // ---------------------------------------------------------

    if (queuedEvent) {
      const { error: updateQueueError } = await supabase
        .from("event_notification_queue")
        .update({
          queued_at: new Date().toISOString(),
        })
        .eq("event_id", event.id);

      if (updateQueueError) {
        console.error(
          "Failed to update queued event:",
          updateQueueError
        );

        throw updateQueueError;
      }

      console.log(
        `Event ${event.id} is already in the notification queue. ` +
        `Updated queued_at. No update email sent.`
      );

      return NextResponse.json({
        success: true,
        operation: "UPDATE",
        notified: false,
        queued: true,
        message:
          "Event is already queued. Queue timestamp updated. No update email sent.",
        sent: 0,
        failed: 0,
      });
    }

    // ---------------------------------------------------------
    // Event is NOT queued
    //
    // The previous notification has already been processed,
    // so send the update email immediately.
    // ---------------------------------------------------------

    const result = await notifySubscribers(
      {
        id: event.id,
        title: event.title,
        category: event.category,
        event_date: event.event_date,
        location: event.location,
        organizer: event.organizer,
        image_url: event.image_url ?? null,
      },
      "UPDATE",
      changedFields
    );

    console.log(
      `Event update notification completed: ` +
      `${result.sent} sent, ${result.failed} failed.`
    );

    return NextResponse.json({
      success: true,
      operation: "UPDATE",
      notified: true,
      queued: false,
      sent: result.sent,
      failed: result.failed,
    });

  } catch (error) {
    console.error(
      "Event notification webhook error:",
      error
    );

    return NextResponse.json(
      {
        error: "Failed to process event notification.",
      },
      { status: 500 }
    );
  }
}